
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/sample?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: 'you need put on environment variable `SPRING_DATASOURCE_PASSWORD`'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      minimum-idle: 10
      maximum-pool-size: 40
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        default_batch_fetch_size: 300
        show_sql: true
        format_sql: true

  liquibase:
    driver-class-name: ${spring.datasource.driver-class-name}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
